<script setup>
import { translate } from '../Composables/useUiPreferences';
import EtfPlannerChart from './EtfPlannerChart.vue';
const props = defineProps({ calculator: { type: Object, required: true }, language: { type: String, default: 'de' } });
const c = props.calculator;
const t = key => translate(props.language, key);
const euro = cents => c.formatCurrency(c.euros(cents));
const strategyName = strategy => t({ 'debt-first': 'Kredite zuerst', balanced: 'Risikoadjustierte Mischung', 'etf-first': 'ETF zuerst' }[strategy]);
const phaseDate = month => `${new Date().getFullYear() + Math.floor((month - 1) / 12)} · ${t('Monat')} ${month}`;
</script>
<template>
  <div class="space-y-5">
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-wide text-indigo-600">{{ t('Risikoadjustierte Empfehlung') }}</p><h2 class="mt-1 text-xl font-bold">{{ strategyName(c.etfPlan.value.recommended.strategy) }}</h2><p class="mt-1 text-sm text-slate-500">{{ t('Sichere Kreditzinsen werden mit der ETF-Rendite nach Kosten, Modellsteuer und Risikoabschlag verglichen.') }}</p></div><div class="rounded-xl bg-emerald-50 px-4 py-3 text-right text-emerald-900"><span class="text-xs">{{ t('Nettovermögen zur Rente') }}</span><strong class="block text-2xl">{{ euro(c.etfPlan.value.recommended.netAssets) }}</strong></div></div>
      <div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-lg bg-orange-50 p-3"><span class="text-xs text-orange-700">{{ t('Höchster Kreditzins') }}</span><strong class="block text-xl text-orange-900">{{ c.formatPercent(c.etfPlan.value.highestLoanRate) }}</strong></div><div class="rounded-lg bg-indigo-50 p-3"><span class="text-xs text-indigo-700">{{ t('ETF-Erwartung brutto') }}</span><strong class="block text-xl text-indigo-900">{{ c.formatPercent(c.inputs.etfExpectedReturn) }}</strong></div><div class="rounded-lg bg-emerald-50 p-3"><span class="text-xs text-emerald-700">{{ t('ETF risikoadjustiert netto') }}</span><strong class="block text-xl text-emerald-900">{{ c.formatPercent(c.etfPlan.value.riskAdjustedEtfReturn) }}</strong></div></div>
      <p class="mt-3 rounded-lg bg-slate-100 p-3 text-sm font-semibold">{{ c.etfPlan.value.highestLoanRate >= c.etfPlan.value.riskAdjustedEtfReturn ? t('Ergebnis: Zusätzliche Tilgung zuerst, beginnend beim teuersten Kredit.') : t('Ergebnis: Nach den Mindestraten fließt das freie Budget zunächst in den ETF.') }}</p>
      <div v-if="c.etfPlan.value.recommended.monthlyShortfall" class="mt-4 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-800">{{ t('Das Monatsbudget liegt unter den vertraglichen Mindestraten. Fehlbetrag:') }} {{ euro(c.etfPlan.value.recommended.monthlyShortfall) }}</div>
      <h3 class="mt-5 text-sm font-bold">{{ t('Verteilung im ersten Monat') }}</h3>
      <div class="mt-2 overflow-x-auto"><table class="w-full text-sm"><thead class="border-b text-left text-xs uppercase text-slate-500"><tr><th class="py-2">{{ t('Ziel') }}</th><th class="text-right">{{ t('Mindestrate') }}</th><th class="text-right">{{ t('Zusätzliche Tilgung') }}</th><th class="text-right">{{ t('Gesamt') }}</th></tr></thead><tbody><tr v-for="row in c.etfPlan.value.recommended.allocation" :key="row.name" class="border-b border-slate-100"><td class="py-2 font-semibold">{{ t(row.name) }}</td><td class="text-right">{{ euro(row.minimum) }}</td><td class="text-right text-emerald-700">{{ euro(row.extra) }}</td><td class="text-right font-bold">{{ euro(row.minimum + row.extra) }}</td></tr><tr class="bg-indigo-50 text-indigo-900"><td class="py-2 font-bold">ETF</td><td></td><td></td><td class="text-right font-bold">{{ euro(c.etfPlan.value.recommended.firstMonthEtf) }}</td></tr></tbody></table></div>
      <h3 class="mt-5 text-sm font-bold">{{ t('Umschichtungsplan bis zur Rente') }}</h3><p class="mt-1 text-xs text-slate-500">{{ t('Nach jeder vollständigen Tilgung wird das freie Monatsbudget automatisch neu verteilt.') }}</p>
      <div class="mt-2 overflow-x-auto"><table class="w-full text-sm"><thead class="border-b text-left text-xs uppercase text-slate-500"><tr><th class="py-2">{{ t('Zeitraum') }}</th><th>{{ t('Priorität für freies Budget') }}</th><th class="text-right">{{ t('Betrag ab Phasenstart') }}</th></tr></thead><tbody><tr v-for="phase in c.etfPlan.value.recommended.phases" :key="`${phase.startMonth}-${phase.target}`" class="border-b border-slate-100"><td class="py-2">{{ phaseDate(phase.startMonth) }} – {{ phaseDate(phase.endMonth) }}</td><td class="font-semibold" :class="phase.target === 'ETF' ? 'text-indigo-700' : 'text-emerald-700'">{{ t(phase.target) }}</td><td class="text-right font-bold">{{ euro(phase.monthlyAmount) }}</td></tr></tbody></table></div>
      <p class="mt-2 text-xs text-amber-700">{{ t('Der Phasenplan unterstellt, dass die dargestellten zusätzlichen Tilgungen vertraglich zulässig sind. Sondertilgungsgrenzen und Vorfälligkeitskosten bitte je Kredit prüfen.') }}</p>
    </section>

    <section class="grid gap-4 lg:grid-cols-3">
      <article v-for="result in c.etfPlan.value.results" :key="result.strategy" class="rounded-xl border bg-white p-4 shadow-sm" :class="result.strategy === c.etfPlan.value.recommended.strategy ? 'border-emerald-400 ring-2 ring-emerald-200' : 'border-slate-200'"><div class="flex justify-between gap-2"><h3 class="font-bold">{{ strategyName(result.strategy) }}</h3><span v-if="result.strategy === c.etfPlan.value.recommended.strategy" class="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-800">{{ t('RISIKOADJUSTIERT') }}</span><span v-else-if="result.strategy === c.etfPlan.value.projectedMaximum.strategy" class="rounded-full bg-indigo-100 px-2 py-1 text-[10px] font-bold text-indigo-800">{{ t('HÖCHSTER ERWARTUNGSWERT') }}</span></div><dl class="mt-4 space-y-2 text-sm"><div class="flex justify-between"><dt>{{ t('ETF nach Modellsteuer') }}</dt><dd class="font-semibold">{{ euro(result.etfAtRetirement) }}</dd></div><div class="flex justify-between"><dt>{{ t('Heutige Kaufkraft') }}</dt><dd class="font-semibold">{{ euro(result.realEtfValue) }}</dd></div><div class="flex justify-between"><dt>{{ t('Restschuld zur Rente') }}</dt><dd class="font-semibold text-orange-700">{{ euro(result.debtAtRetirement) }}</dd></div><div class="flex justify-between border-t pt-2"><dt>{{ t('Nettovermögen') }}</dt><dd class="font-bold text-emerald-700">{{ euro(result.netAssets) }}</dd></div><div class="flex justify-between"><dt>{{ t('Modell-Entnahme/Monat') }}</dt><dd class="font-semibold">{{ euro(result.monthlyRetirementWithdrawal) }}</dd></div><div class="flex justify-between"><dt>{{ t('Kreditzinsen gesamt') }}</dt><dd class="font-semibold">{{ euro(result.totalInterest) }}</dd></div></dl></article>
    </section>

    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 class="font-bold">{{ t('Vermögens- und Restschuldverlauf') }}</h2><p class="mt-1 text-xs text-slate-500">{{ strategyName(c.etfPlan.value.recommended.strategy) }} · {{ t('nominale Modellwerte') }}</p></div><EtfPlannerChart class="mt-4" :rows="c.etfPlan.value.recommended.timeline" :locale="language" /></section>
  </div>
</template>
